### ISSUE TITLE
Linux Functionality

### ISSUE THREAD

**Issue by unkn0wnfuncti0n** [mswieboda/crayster#1]
Removing the use of the -i flag from sed command for BSD/Linux cross-compliance.  *
`@sed -e 's|___CRAYSTER_SRC_DIR___|$(CRAYSTER_SRC_DIR)|' ./src/crayster.cr > ./src/crayster.new`
`@mv -- ./src/crayster.new ./src/crayster.cr`
_*still have to manually set the LD_LIBRARY_PATH in the crayster generated apps makefile._

**Comment by mswieboda** [comment]
@unkn0wnfuncti0n did you fix what you needed? I'm no `Makefile` expert, so if it could be enhanced, and made to work best across Linux/Mac etc, I'm all for improvements!

This project has definitely been a WIP so pretty rough on the edges, but hopefully you've found it useful to kick up a new cray/RayLib project. Hopefully you were able to get the Linux compiled `libraylib.so` via [cray Makefile](https://github.com/tapgg/cray/blob/master/Makefile) to `./lib_ext`? Please let me know if I can help with anything.

**Comment by unkn0wnfuncti0n** [comment]
@mswieboda I haven't been able to test the modified makefile on Mac yet but it should work on both Linux/Mac. I will submit that soon.
I built RayLib with cmake and changed the library paths manually in the makefile generated by the crayster command. Not ideal, but was able to get up and running on a blank system in less than 5 minutes which I count as a win.
Thanks for putting this out it has been very useful.
